version: 2.1
defaults: &defaults
  working_directory: ~/docker-awscli
  machine:
    node:
      version: 5.8.0
    services:
      - docker

jobs:
  build:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: yarn build

workflows:
  version: 2.1

  general:
    jobs:
      - build
